name: scheduled_workflow


on:
    workflow_dispatch:
    #schedule:
     # - cron: "*/15 * * * *"

jobs:
    scheduled_job:
        runs-on: ubuntu-latest

        steps:
          - name: print mesg
            run: echo "Running the Scheduled task"